name: Energy Schema
version: "0.1.4"
slug: energy_schema
description: Живая однолинейная схема энергосистемы VELMUR (Go renderer)
url: https://github.com/Sergii-Kirichok/ha-energy-schema
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 8099
homeassistant_api: true
hassio_api: true
map:
  - homeassistant_config:rw
options:
  refresh_seconds: 3
  ha_url: "http://homeassistant:8123"
  ha_token: ""
  title: "Энергосистема"
schema:
  refresh_seconds: int(1,60)
  ha_url: str
  ha_token: str?
  title: str?
