name: Energy Schema
version: "0.1.2"
slug: energy_schema
description: Живая однолинейная схема энергосистемы VELMUR (Go renderer)
url: https://github.com/Sergii-Kirichok/ha-energy-schema
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:sitemap-outline
panel_title: Схема
homeassistant_api: true
options:
  refresh_seconds: 3
schema:
  refresh_seconds: int(1,60)
